version: '2'
services:
    proxy:
        image: nginx:latest
        volumes:
            - "./nginx.conf:/etc/nginx/nginx.conf:ro"
            - "./ssl:/etc/nginx/ssl:ro"
        ports:
            - "80:80"
            - "443:443"
